name: 'Create push subscription'
description: 'Create a Google Pub/Sub push subscription for an Octue service.'
author: 'Marcus Lugg'
inputs:
  project_name:
    description: 'The name of the Google Cloud project to create the subscription in.'
    required: true
  service_id:
    description: 'The ID of the Octue service in kebab case, optionally preceded by an organisation name (e.g. `wake-service` or `octue/example-service`)).'
    required: true
  push_endpoint:
    description: "The HTTP/HTTPS endpoint of the service to push to. It should be fully formed and include the 'https://' prefix."
    required: true
  revision_tag:
    description: 'The tag used as a suffix to the service ID when creating a Service Revision Unique Identifier (e.g. 1.0.7).'
    required: false

runs:
   using: 'docker'
   image: '../Dockerfile'
   args:
     - ${{ inputs.project_name }}
     - ${{ inputs.service_id }}
     - ${{ inputs.push_endpoint }}
     - ${{ inputs.revision_tag }}
