name: test

on:
  push:
    branches-ignore:
      - main

jobs:
  create-push-subscription:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.8.1
        with:
          # NOTE: If setting create_credentials_file=true, .dockerignore file must include `gha-creds-*.json` to avoid baking these credentials into build
          create_credentials_file: true
          workload_identity_provider: 'projects/481503880524/locations/global/workloadIdentityPools/github-actions-pool-2/providers/github-actions-provider-2'
          service_account: 'gha-sdk-python@octue-amy.iam.gserviceaccount.com'

      - uses: octue/create-push-subscription@feature/add-github-action
        with:
          project_name: octue-amy
          service_id: octue/my-test-service
          push_endpoint: https://example.com/endpoint
          revision_tag: 1.3.4
