name: test

on:
  push:
    branches-ignore:
      - main

jobs:
  create-push-subscription:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest
    steps:
      - uses: octue/create-push-subscription@feature/add-github-action
        with:
          project_name: octue-amy
          service-id: octue/my-test-service
          push_endpoint: https://example.com/endpoint
          revision_tag: 1.3.4
